mod.id = "tintedsoil"
mod.name = "Tinted Soil"
mod.group = "com.minerguy341.tintedsoil"
mod.version = "0.1.0"

deps.fabric_loader = "0.19.5"
loomx.loom_version = "1.17.20"

["1.20.1"]
mod.mc_releases = ["1.20.1"]

[fabric."1.20.1"]
mod.mc_compat = "~1.20.1"
deps.fabric_api = "0.92.12+1.20.1"

["1.21.1"]
mod.mc_releases = ["1.21", "1.21.1"]

[fabric."1.21.1"]
mod.mc_compat = ">=1.21 <=1.21.1"
deps.fabric_api = "0.116.17+1.21.1"

[neoforge."1.21.1"]
mod.mc_compat = "[1.21, 1.21.1]"
deps.neo_loader = "21.1.250"

["1.21.8"]
mod.mc_releases = ["1.21.6", "1.21.7", "1.21.8"]

[fabric."1.21.8"]
mod.mc_compat = ">=1.21.6 <=1.21.8"
deps.fabric_api = "0.136.1+1.21.8"

[neoforge."1.21.8"]
mod.mc_compat = "[1.21.6, 1.21.8]"
deps.neo_loader = "21.8.54"
